@rootURL = http://localhost:3000
@apiEP = {{rootURL}}/api/admin/v1
@authEP = {{apiEP}}/auth/login

@productsEP = {{apiEP}}/products

@categoriesEP = {{apiEP}}/categories

@ordersEP = {{apiEP}}/orders

@reviewsEP = {{apiEP}}/reviews

# Customer Backend APIs (Base: /api/customer/v1/)
# Authentication APIs:
# POST /api/customer/v1/auth/signup
# POST /api/customer/v1/auth/login     
# GET /api/customer/v1/auth/verify/:token
# POST /api/customer/v1/auth/refresh-token
# Product APIs:



###
POST {{authEP}}
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}

### create a new product

POST {{productsEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTQxODQ0NSwiZXhwIjoxNzY5NTA0ODQ1fQ.RMR4Ho6Kk_fJyMK6GBdBJso4m-agVj7kEt9CNQjreNw
Content-Type: application/json

{
  "name": "Google Pixel 8",
  "description": "Google's latest flagship phone",
  "price": 899,
  "stock": 12,
  "category": "695a1fd327ad281b903a6187",
  "images": ["pixel8-front.jpg", "pixel8-back.jpg"]
}

### update product details
PUT {{productsEP}}/695a21df27ad281b903a6193
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTQxODQ0NSwiZXhwIjoxNzY5NTA0ODQ1fQ.RMR4Ho6Kk_fJyMK6GBdBJso4m-agVj7kEt9CNQjreNw
Content-Type: application/json

{
  "price": 2400,
  "stock": 25
}

### delete a product
DELETE {{productsEP}}/695a242627ad281b903a61a1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTYwMDcwNCwiZXhwIjoxNzY5Njg3MTA0fQ.APl2JAYkJHZU0OHEPvP76gh7iWfFUylrW3sfm9W-VCw

### create a new category
POST {{categoriesEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTYwMTIxMSwiZXhwIjoxNzY5Njg3NjExfQ.fkc9bSU88hLYsFi8fsCLL0opxbUF6KIS8r6rup8GLfo
Content-Type: application/json

{
  "name": "Tablets"
}

### update category details
PUT {{categoriesEP}}/695a1fd327ad281b903a6187
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTY3NDAwMywiZXhwIjoxNzY5NzYwNDAzfQ.C2u1AO20QpC_x08huznNOl75Jvnz04O6sTTalpp9wug
Content-Type: application/json

{
  "name": "Smartphones"
}

### delete a category
DELETE {{categoriesEP}}/695a1fd327ad281b903a6187
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTY3NDAwMywiZXhwIjoxNzY5NzYwNDAzfQ.C2u1AO20QpC_x08huznNOl75Jvnz04O6sTTalpp9wug

### get all orders
GET {{ordersEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTY3NTEwMywiZXhwIjoxNzY5NzYxNTAzfQ.Lc905g1zwoorYSQxSjPc4ir8Q-PX3pRYwFuILg6K4EI

### update order status
PUT {{ordersEP}}/69674e8b4f3195a2dc2f4412/status
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTY3NTEwMywiZXhwIjoxNzY5NzYxNTAzfQ.Lc905g1zwoorYSQxSjPc4ir8Q-PX3pRYwFuILg6K4EI
Content-Type: application/json

{
  "status": "shipped"
}

###
PUT {{reviewsEP}}/6975d199230e61c91d9db2b8/approve
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTY3NjAwNiwiZXhwIjoxNzY5NzYyNDA2fQ.wBatbOcYOabUnrWbV1Q1gVqVECZvq98VRqSykPHSeac

###
DELETE {{reviewsEP}}/6975d199230e61c91d9db2b8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIl9pZCI6IjY5NzcyNTg1ZDIxYzIyYzU4MDUwMTgzOSIsImlhdCI6MTc2OTY3NjAwNiwiZXhwIjoxNzY5NzYyNDA2fQ.wBatbOcYOabUnrWbV1Q1gVqVECZvq98VRqSykPHSeac